server {
    listen 80;
    server_name localhost;

    location / {
        root /app;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Cache control for events.json since it is updated weekly
    location = /events.json {
        root /app;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }
}
